name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
main: de.derfrzocker.custom.ore.generator.CustomOreGenerator
api-version: 1.13
load: STARTUP
commands:
  oregen:
    permission: "custom.ore.gen"

permissions:
  custom.ore.gen:
    description: "Base permission"
    default: op
  custom.ore.gen.*:
    description: "Gives access to all Custom Ore Generation commands and functions"
    default: op
    children:
      custom.ore.gen: true
      custom.ore.gen.set.*: true
      custom.ore.gen.reload: true
      custom.ore.gen.create: true
  custom.ore.gen.set.*:
    description: "Gives access to the subcommand 'set value', 'set biome' and 'set customdata'"
    default: op
    children:
      custom.ore.gen: true
      custom.ore.gen.set.value: true
      custom.ore.gen.set.biome: true
      custom.ore.gen.set.customdata: true
      custom.ore.gen.set.replacematerial: true
  custom.ore.gen.set.value:
    description: "Gives access to the subcommand 'set value'"
    default: op
    children:
      custom.ore.gen: true
  custom.ore.gen.set.biome:
    description: "Gives access to the subcommand 'set biome'"
    default: op
    children:
      custom.ore.gen: true
  custom.ore.gen.set.customdata:
    description: "Gives access to the subcommand 'set customdata'"
    default: op
    children:
      custom.ore.gen: true
  custom.ore.gen.set.replacematerial:
    description: "Gives access to the subcommand 'set replacematerial'"
    default: op
    children:
      custom.ore.gen: true
  custom.ore.gen.reload:
    description: "Gives access to the subcommand 'reload'"
    default: op
    children:
      custom.ore.gen: true
  custom.ore.gen.create:
    description: "Gives access to the subcommand 'create'"
    default: op
    children:
      custom.ore.gen: true