name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
main: de.derfrzocker.custom.ore.generator.CustomOreGenerator
api-version: 1.13
load: STARTUP
softdepend:
  - ItemMods
  - Oraxen
commands:
  oregen:
    permission: "custom.ore.gen"
    description: "Main command of Custom-Ore-Generator plugin"

permissions:
  custom.ore.gen:
    description: "Base permission"
    default: op
  custom.ore.gen.*:
    description: "Gives access to all Custom Ore Generation commands and functions"
    default: op
    children:
      custom.ore.gen: true
      custom.ore.gen.set.*: true
      custom.ore.gen.add.*: true
      custom.ore.gen.reload: true
      custom.ore.gen.create: true
  custom.ore.gen.set.*:
    description: "Gives access to all 'set' subcommands"
    default: op
    children:
      custom.ore.gen.set: true
      custom.ore.gen.set.value.*: true
      custom.ore.gen.set.biome: true
      custom.ore.gen.set.customdata: true
      custom.ore.gen.set.replace-material: true
      custom.ore.gen.set.select-material: true
      custom.ore.gen.set.position: true
  custom.ore.gen.set:
    description: "Base permission of the 'set' subcommand"
    default: op
    children:
      custom.ore.gen: true
  custom.ore.gen.set.value.*:
    description: "Gives access to all 'set value' subcommands"
    default: op
    children:
      custom.ore.gen.set.value: true
      custom.ore.gen.set.value.ore-generator: true
      custom.ore.gen.set.value.block-selector: true
  custom.ore.gen.set.value:
    description: "Base permission of the 'set value' subcommand"
    default: op
    children:
      custom.ore.gen.set: true
  custom.ore.gen.set.value.ore-generator:
    description: "Gives access to the subcommand 'set value ore-generator'"
    default: op
    children:
      custom.ore.gen.set.value: true
  custom.ore.gen.set.value.block-selector:
    description: "Gives access to the subcommand 'set value block-selector'"
    default: op
    children:
      custom.ore.gen.set.value: true
  custom.ore.gen.set.biome:
    description: "Gives access to the subcommand 'set biome'"
    default: op
    children:
      custom.ore.gen.set: true
  custom.ore.gen.set.customdata:
    description: "Gives access to the subcommand 'set customdata'"
    default: op
    children:
      custom.ore.gen.set: true
  custom.ore.gen.set.replace-material:
    description: "Gives access to the subcommand 'set replacematerial'"
    default: op
    children:
      custom.ore.gen.set: true
  custom.ore.gen.set.select-material:
    description: "Gives access to the subcommand 'set selectmaterial'"
    default: op
    children:
      custom.ore.gen.set: true
  custom.ore.gen.set.position:
    description: "Gives access to the subcommand 'set position'"
    default: op
    children:
      custom.ore.gen.set: true
  custom.ore.gen.add.*:
    description: "Gives access to all 'add' subcommands"
    default: op
    children:
      custom.ore.gen.add: true
      custom.ore.gen.add.ore-config: true
  custom.ore.gen.add:
    description: "Base permission of the 'add' subcommand"
    default: op
    children:
      custom.ore.gen: true
  custom.ore.gen.add.ore-config:
    description: "Base permission of the 'add ore-config' subcommand"
    default: op
    children:
      custom.ore.gen.add: true
  custom.ore.gen.reload:
    description: "Gives access to the subcommand 'reload'"
    default: op
    children:
      custom.ore.gen: true
  custom.ore.gen.create:
    description: "Gives access to the subcommand 'create'"
    default: op
    children:
      custom.ore.gen: true